import contextlib
import hashlib
import io
import json
import subprocess
import sys
from pathlib import Path

from flask import Flask, jsonify, request, send_from_directory

from auth.otp import OTP
from auth.pond_auth import PondAuth
from cert.verify import verify_certificate
from crypto.aes_crypto import AESCrypto
from gan.attacker import Attacker
from gan.cipher_attack import CipherAttack
from gan.gan_key import GANKey
from myssl.handshake import Handshake
from steg.image_steg import ImageSteg
from tool_practical import (
    BASE_DIR as PRACTICAL_BASE_RELATIVE,
    demo_gnupg,
    demo_netcat_guide,
    demo_openssl,
    demo_password_attack,
    demo_wireshark_guide,
    list_tools,
)


ROOT = Path(__file__).resolve().parent
DATA_DIR = ROOT / "data"
PRACTICAL_BASE_DIR = ROOT / PRACTICAL_BASE_RELATIVE
CERT_PATH = ROOT / "cert" / "my_cert.json"
INPUT_IMAGE = DATA_DIR / "input.png"
OUTPUT_IMAGE = DATA_DIR / "output.png"
SESSION_FILE = DATA_DIR / "session.bin"
GAN_NOISE_FILE = DATA_DIR / "gan_noise.bin"

app = Flask(__name__)


def rel(path):
    return str(path.relative_to(ROOT)).replace("\\", "/")


def file_info(path, purpose):
    path = Path(path)
    info = {
        "path": rel(path),
        "purpose": purpose,
        "exists": path.exists(),
        "size": path.stat().st_size if path.exists() else 0,
        "preview": None,
        "kind": "file",
    }

    if path.suffix.lower() in {".png", ".jpg", ".jpeg"}:
        info["kind"] = "image"
        info["url"] = "/files/" + rel(path)
    elif path.exists() and path.stat().st_size <= 4096 and path.suffix.lower() not in {".bin", ".gpg", ".enc", ".pem"}:
        try:
            info["preview"] = path.read_text(encoding="utf-8", errors="replace")[:800]
        except OSError:
            info["preview"] = None

    return info


def sha256_preview(data):
    return hashlib.sha256(data).hexdigest()[:24]


def capture_output(fn):
    stream = io.StringIO()
    try:
        with contextlib.redirect_stdout(stream), contextlib.redirect_stderr(stream):
            fn()
        return {"ok": True, "output": stream.getvalue()}
    except Exception as exc:
        return {"ok": False, "output": stream.getvalue() + "\n" + str(exc)}


def artifact_list():
    artifacts = [
        file_info(INPUT_IMAGE, "Original carrier image used by image steganography."),
        file_info(OUTPUT_IMAGE, "Stego image containing the AES ciphertext."),
        file_info(SESSION_FILE, "Session key generated by the SSL-style handshake."),
        file_info(GAN_NOISE_FILE, "GAN-generated or random noise mixed into the final AES key."),
        file_info(CERT_PATH, "JSON certificate verified during handshake and access checks."),
    ]

    practical_purposes = {
        "openssl": "OpenSSL generated keys, certificate, encrypted file, and decrypted message.",
        "gnupg": "GnuPG message, signature, encrypted output, decrypted output, and local keyring.",
        "password_attack": "Weak hash, wordlist, and cracked-password evidence.",
        "netcat": "Plaintext, AES ciphertext, and local decrypt check for network transfer.",
    }

    if PRACTICAL_BASE_DIR.exists():
        for folder, purpose in practical_purposes.items():
            folder_path = PRACTICAL_BASE_DIR / folder
            if folder_path.exists():
                for item in sorted(folder_path.iterdir()):
                    if item.is_file():
                        artifacts.append(file_info(item, purpose))

    return artifacts


@app.get("/api/status")
def status():
    tool_result = capture_output(list_tools)
    return jsonify(
        {
            "ok": True,
            "modules": [
                {"name": "Handshake", "status": "available"},
                {"name": "Certificate Verify", "status": "available"},
                {"name": "GAN Key", "status": "available"},
                {"name": "AES Crypto", "status": "available"},
                {"name": "Image Steg", "status": "available"},
                {"name": "OTP", "status": "available"},
                {"name": "Pond Auth", "status": "available"},
                {"name": "Practical Tools", "status": "available"},
            ],
            "tools": tool_result["output"],
            "artifacts": artifact_list(),
        }
    )


@app.post("/api/hide")
def hide_secret():
    payload = request.get_json(silent=True) or {}
    secret = payload.get("secret", "").strip() or "Professor demo secret message"
    steps = []

    if not INPUT_IMAGE.exists():
        return jsonify({"ok": False, "error": "data/input.png is missing", "steps": steps}), 400

    h = Handshake()
    with contextlib.redirect_stdout(io.StringIO()):
        h.client_hello()
        h.server_hello()
        cert = h.send_certificate()
        cert_ok = h.verify_certificate(cert)
        session_key = h.generate_session_key()

    steps.append({"label": "Handshake complete", "status": "success", "detail": "Client/server hello completed."})
    steps.append(
        {
            "label": "Certificate valid" if cert_ok else "Certificate invalid",
            "status": "success" if cert_ok else "danger",
            "detail": "Certificate hash matched cert/my_cert.json." if cert_ok else "Certificate hash mismatch.",
        }
    )

    if not cert_ok:
        return jsonify({"ok": False, "error": "Handshake certificate verification failed", "steps": steps}), 400

    gk = GANKey()
    attacker = Attacker()
    cipher_attack = CipherAttack()
    gan_noise = gk.generate_noise()
    final_key = session_key + gan_noise
    attacker_score = attacker.try_key(final_key)

    if attacker_score < 0.3:
        gan_noise = gk.generate_noise()
        final_key = session_key + gan_noise
        attacker_score = attacker.try_key(final_key)

    aes = AESCrypto(final_key)
    ciphertext = aes.encrypt(secret)
    ImageSteg().hide(str(INPUT_IMAGE), str(OUTPUT_IMAGE), ciphertext)
    cipher_score = cipher_attack.check_cipher(ciphertext)

    otp = OTP()
    code = otp.generate()
    otp_ok = otp.verify(code)

    pond = PondAuth(aes.key, 5)
    with contextlib.redirect_stdout(io.StringIO()):
        pond.generate()
    pond_ok = pond.verify(pond.correct)
    cert_file_ok = verify_certificate(str(CERT_PATH))

    steps.extend(
        [
            {"label": "Session key generated", "status": "success", "detail": rel(SESSION_FILE)},
            {
                "label": "GAN noise generated",
                "status": "success",
                "detail": rel(GAN_NOISE_FILE),
            },
            {
                "label": "Final AES key derived",
                "status": "info",
                "detail": "SHA-256 key preview: " + sha256_preview(final_key),
            },
            {
                "label": "Ciphertext created",
                "status": "success",
                "detail": ciphertext[:96] + ("..." if len(ciphertext) > 96 else ""),
            },
            {"label": "Ciphertext hidden in image", "status": "success", "detail": rel(OUTPUT_IMAGE)},
            {
                "label": "OTP, pond, and certificate checks passed",
                "status": "success" if otp_ok and pond_ok and cert_file_ok else "danger",
                "detail": "OTP verified, pond " + str(pond.correct) + " selected, certificate rechecked.",
            },
        ]
    )

    return jsonify(
        {
            "ok": otp_ok and pond_ok and cert_file_ok,
            "secretLength": len(secret),
            "attackerScore": round(float(attacker_score), 4),
            "cipherAttackScore": round(float(cipher_score), 4),
            "ciphertextPreview": ciphertext[:140] + ("..." if len(ciphertext) > 140 else ""),
            "outputImage": "/files/" + rel(OUTPUT_IMAGE),
            "steps": steps,
            "artifacts": artifact_list(),
        }
    )


@app.post("/api/extract")
def extract_secret():
    missing = [rel(path) for path in (SESSION_FILE, GAN_NOISE_FILE, OUTPUT_IMAGE) if not path.exists()]
    if missing:
        return jsonify({"ok": False, "error": "Missing required artifacts: " + ", ".join(missing)}), 400

    h = Handshake()
    session_key = h.load_session_key()
    gan_noise = GANKey().load_noise()
    final_key = session_key + gan_noise
    aes = AESCrypto(final_key)
    ciphertext = ImageSteg().extract(str(OUTPUT_IMAGE))
    secret = aes.decrypt(ciphertext)

    steps = [
        {"label": "Session key loaded", "status": "success", "detail": rel(SESSION_FILE)},
        {"label": "GAN noise loaded", "status": "success", "detail": rel(GAN_NOISE_FILE)},
        {"label": "Final AES key rebuilt", "status": "info", "detail": "SHA-256 key preview: " + sha256_preview(final_key)},
        {
            "label": "Ciphertext extracted",
            "status": "success",
            "detail": ciphertext[:96] + ("..." if len(ciphertext) > 96 else ""),
        },
        {"label": "Secret decrypted", "status": "success", "detail": secret},
    ]

    return jsonify(
        {
            "ok": True,
            "secret": secret,
            "ciphertextPreview": ciphertext[:140] + ("..." if len(ciphertext) > 140 else ""),
            "steps": steps,
        }
    )


@app.get("/api/artifacts")
def artifacts():
    return jsonify({"ok": True, "artifacts": artifact_list()})


@app.post("/api/tools/<tool_name>")
def practical_tool(tool_name):
    demos = {
        "list": list_tools,
        "openssl": demo_openssl,
        "gnupg": demo_gnupg,
        "password-attack": demo_password_attack,
        "netcat": demo_netcat_guide,
        "wireshark": demo_wireshark_guide,
    }

    if tool_name not in demos:
        return jsonify({"ok": False, "error": "Unknown practical tool: " + tool_name}), 404

    result = capture_output(demos[tool_name])
    return jsonify({"ok": result["ok"], "tool": tool_name, "output": result["output"], "artifacts": artifact_list()})


@app.get("/files/<path:relative_path>")
def files(relative_path):
    target = (ROOT / relative_path).resolve()
    if not str(target).startswith(str(ROOT)):
        return jsonify({"ok": False, "error": "Invalid file path"}), 400
    return send_from_directory(target.parent, target.name)


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5000, debug=True)
